{% set name = "django-plotly-dash" %}
{% set version = "2.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f64611d0c2ed9f0319eadb8ffb886a012816406ff0e23232371037f4d66962aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - plotly
    - dash >=2.0,<3.0
    - dpd_components
    - dash-bootstrap-components
    - dash-core-components
    - dash-html-components
    - dash-table
    - channels >=4.0
    - django >=4.0.0
    - flask >=1.0.2
    - werkzeug

test:
  imports:
    - django_plotly_dash
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/GibbsConsulting/django-plotly-dash
  summary: Django use of plotly dash apps through template tags
  dev_url: https://github.com/GibbsConsulting/django-plotly-dash
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
